export enum ERR_CODE {
    INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
    BAD_REQUEST = 'BAD_REQUEST',
    TOO_MANY_REQUEST = 'TOO_MANY_REQUEST',

    // User
    USERNAME_IS_EXIST = 'USERNAME_IS_EXIST',
    USERNAME_OR_PASSWORD_NOT_MATCH = 'USERNAME_OR_PASSWORD_NOT_MATCH',
}
